language: python
python:
    - "2.7"
before_install:
    # copied from gensim
    - wget 'http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh' -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
install:
    - conda create --yes -n cfl-test python=$TRAVIS_PYTHON_VERSION pip atlas numpy scipy
    - source activate cfl-test
    - make install
script: "nosetests tests/"
